- name: Add Microsoft GPG key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: "Visual Studio Code"
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code
  yum:
    name: code
    state: latest

#Dont run as root
- name: Install desired VS Code extensions
  become: false
  shell: "code --install-extension {{ item }} --force"
  loop:
    - redhat.ansible
    - redhat.vscode-yaml
  register: vscode_extensions
  changed_when: "'already installed' not in vscode_extensions.stdout"

- name: Display installed extensions
  debug:
    msg: "Installed extensions: {{ vscode_extensions.results | map(attribute='item') | list }}"
